# Generated by Django 4.1.3 on 2022-12-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_remove_car_quantity'),
        ('authApp', '0003_userprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='watch_list',
            field=models.ManyToManyField(null=True, to='myApp.car'),
        ),
    ]
