# Generated by Django 4.1.3 on 2022-12-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='static/images/no-image-product.jpg', upload_to='static/images'),
        ),
    ]
