# Generated by Django 4.1.3 on 2022-12-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='media/images/no-image-product.jpg', upload_to='media/images.'),
        ),
    ]
