# Generated by Django 4.1.3 on 2022-12-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='static/no-image-product.jpg', upload_to='images'),
        ),
    ]
