# Generated by Django 4.1.3 on 2022-12-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_alter_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
    ]
