# Generated by Django 4.1.3 on 2022-12-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_remove_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='static/images/no-image-product.jpg', upload_to='images'),
        ),
    ]
