# Generated by Django 4.1.3 on 2022-12-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(choices=[('mb', 'Mercedes-Benz'), ('bw', 'BMW'), ('au', 'Audi'), ('ty', 'Toyota'), ('ns', 'Nissan'), ('mi', 'Mitsubishi')], max_length=2),
        ),
    ]
