# Generated by Django 4.1.3 on 2022-12-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_alter_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(choices=[('Mercedes-Benz', 'Mercedes-Benz'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('Toyota', 'Toyota'), ('Nissan', 'Nissan'), ('Mitsubishi', 'Mitsubishi')], max_length=32),
        ),
    ]
