# Generated by Django 4.1.3 on 2022-12-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_alter_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(choices=[('mb', 'Mercedes-Benz'), ('bw', 'BMW'), ('au', 'Audi'), ('ty', 'Toyota'), ('ns', 'Nissan'), ('mt', 'Mitsubishi')], max_length=32),
        ),
    ]
