# Generated by Django 4.1.3 on 2022-12-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_alter_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='static/images/no-image-product.jpg', upload_to='images/products'),
        ),
    ]
