# Generated by Django 4.1.3 on 2022-12-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_car_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='quantity',
        ),
    ]
